try:
    pass
except ValueError as e:
    pass
except KeyError:
    pass
finally:
    pass